import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { base44 } from '@/api/base44Client';
import { HelpCircle, Loader2, ChevronDown, ChevronUp } from 'lucide-react';

export default function AutoGeneratedFAQ({ courseId }) {
  const [loading, setLoading] = useState(false);
  const [faqs, setFaqs] = useState(null);
  const [expandedIdx, setExpandedIdx] = useState(null);

  const generateFAQ = async () => {
    setLoading(true);
    try {
      const { data } = await base44.functions.invoke('generateFAQ', { course_id: courseId });
      setFaqs(data);
    } catch (error) {
      console.error('FAQ generation error:', error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <Card className="card-glow">
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle className="text-white flex items-center gap-2">
            <HelpCircle className="w-5 h-5" />
            Auto-Generated FAQ
          </CardTitle>
          <Button size="sm" onClick={generateFAQ} disabled={loading}>
            {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : 'Generate'}
          </Button>
        </div>
      </CardHeader>
      <CardContent className="space-y-2">
        {faqs?.faqs?.map((faq, idx) => (
          <div key={idx} className="bg-gray-800/50 rounded-lg overflow-hidden">
            <button
              onClick={() => setExpandedIdx(expandedIdx === idx ? null : idx)}
              className="w-full flex items-center justify-between p-3 text-left hover:bg-gray-700/50 transition"
            >
              <span className="font-medium text-white text-sm">{faq.question}</span>
              {expandedIdx === idx ? (
                <ChevronUp className="w-4 h-4 text-gray-400" />
              ) : (
                <ChevronDown className="w-4 h-4 text-gray-400" />
              )}
            </button>
            {expandedIdx === idx && (
              <div className="p-3 pt-0 text-sm text-gray-300">
                {faq.answer}
              </div>
            )}
          </div>
        ))}
      </CardContent>
    </Card>
  );
}