import React, { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Users, MessageSquare, TrendingUp, Lightbulb } from 'lucide-react';
import ExpertIdentification from '@/components/community/ExpertIdentification';
import SmartContentSuggester from '@/components/community/SmartContentSuggester';
import AutoGeneratedFAQ from '@/components/community/AutoGeneratedFAQ';
import EngagementAnalytics from '@/components/community/EngagementAnalytics';

export default function CommunityAIHub() {
  const [selectedCourse, setSelectedCourse] = useState(null);

  const { data: user } = useQuery({
    queryKey: ['user'],
    queryFn: () => base44.auth.me()
  });

  const { data: enrollments } = useQuery({
    queryKey: ['enrollments', user?.email],
    queryFn: () => base44.entities.Enrollment.filter({ student_email: user?.email }),
    enabled: !!user?.email
  });

  const { data: createdCourses } = useQuery({
    queryKey: ['created-courses', user?.email],
    queryFn: () => base44.entities.Course.filter({ creator_email: user?.email }),
    enabled: !!user?.email
  });

  const allCourses = [...(enrollments || []), ...(createdCourses || [])];
  const uniqueCourses = Array.from(new Map(allCourses.map(c => [c.course_id || c.id, c])).values());

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-slate-100 p-6">
      <div className="max-w-7xl mx-auto space-y-6">
        {/* Header */}
        <div className="bg-gradient-to-r from-purple-600 to-pink-600 rounded-2xl p-8 text-white">
          <h1 className="text-3xl font-bold mb-2">Community AI Hub</h1>
          <p className="text-purple-100">
            AI-powered insights, expert identification, and smart recommendations for your learning communities
          </p>
        </div>

        {/* Course Selector */}
        <Card>
          <CardHeader>
            <CardTitle>Select a Course</CardTitle>
          </CardHeader>
          <CardContent>
            <Select value={selectedCourse} onValueChange={setSelectedCourse}>
              <SelectTrigger>
                <SelectValue placeholder="Choose a course to view AI insights" />
              </SelectTrigger>
              <SelectContent>
                {uniqueCourses.map((course) => (
                  <SelectItem key={course.id} value={course.id}>
                    {course.title}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </CardContent>
        </Card>

        {selectedCourse && (
          <Tabs defaultValue="experts" className="space-y-6">
            <TabsList className="grid w-full grid-cols-4">
              <TabsTrigger value="experts">
                <Users className="w-4 h-4 mr-2" />
                Experts
              </TabsTrigger>
              <TabsTrigger value="suggestions">
                <Lightbulb className="w-4 h-4 mr-2" />
                Smart Suggestions
              </TabsTrigger>
              <TabsTrigger value="faq">
                <MessageSquare className="w-4 h-4 mr-2" />
                Auto FAQ
              </TabsTrigger>
              <TabsTrigger value="analytics">
                <TrendingUp className="w-4 h-4 mr-2" />
                Analytics
              </TabsTrigger>
            </TabsList>

            <TabsContent value="experts" className="space-y-4">
              <ExpertIdentification courseId={selectedCourse} />
            </TabsContent>

            <TabsContent value="suggestions" className="space-y-4">
              <SmartContentSuggester courseId={selectedCourse} />
            </TabsContent>

            <TabsContent value="faq" className="space-y-4">
              <AutoGeneratedFAQ courseId={selectedCourse} />
            </TabsContent>

            <TabsContent value="analytics" className="space-y-4">
              <EngagementAnalytics courseId={selectedCourse} />
            </TabsContent>
          </Tabs>
        )}

        {!selectedCourse && (
          <Card className="border-dashed">
            <CardContent className="flex items-center justify-center py-12">
              <div className="text-center text-gray-500">
                <Users className="w-12 h-12 mx-auto mb-3 opacity-50" />
                <p>Select a course above to view AI-powered community insights</p>
              </div>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
}